name: Build and Publish Nuget Packages
run-name: ${{ format('Release {0}', inputs.release_type)}} Package by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: The type of release
        options:
        - Snapshot
        - Patch
        - Minor
        - Major
      publish_vulnerabilities:
        type: string
        default: "true"
      dotnet_version:
        type: string
        default: "6.0"
      vulnerability_failure_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised. Must be one of ['CRITICAL', 'CRITICAL,HIGH' or 'CRITICAL,HIGH,MEDIUM'] (without space in between).
        type: string
        default: 'CRITICAL,HIGH'

jobs:
  build-and-pubish:
    name: Build and publish nupkg to Nuget repository
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-to-nuget-versioned.yaml@kcc-UID2-5248-nuget-vulnerability-scan
    with:
      release_type: ${{ inputs.release_type }}
      dotnet_version: ${{ inputs.dotnet_version }}
      publish_vulnerabilities: ${{ inputs.publish_vulnerabilities }}
      vulnerability_failure_severity: ${{ inputs.vulnerability_failure_severity }}
    secrets: inherit
